name = "DroneTransportation"
uuid = "f201d1f2-d2e3-41e2-8744-e7196cc3389d"
authors = ["jc-bao <jc-bao@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
